name: Analyze Language Stats

on:
  push:
    branches:
      - main  

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Run cloc
        run: cloc .
